# Generated by Django 3.1.1 on 2024-10-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='available_emergency_doctors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='services',
            name='patients_in_queue',
            field=models.IntegerField(default=0),
        ),
    ]
