# Generated by Django 3.1.1 on 2024-10-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20241015_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='available_beds',
        ),
        migrations.RemoveField(
            model_name='services',
            name='available_emergency_doctors',
        ),
        migrations.RemoveField(
            model_name='services',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='services',
            name='patients_in_queue',
        ),
        migrations.RemoveField(
            model_name='services',
            name='total_beds',
        ),
        migrations.AddField(
            model_name='services',
            name='service',
            field=models.CharField(default='', max_length=60),
        ),
    ]
