# Generated by Django 3.1.1 on 2024-10-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20241015_2053'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='facility',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='service',
        ),
        migrations.AddField(
            model_name='facility',
            name='title',
            field=models.CharField(default='', max_length=60),
        ),
    ]
