# Generated by Django 3.1.1 on 2024-10-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_availability_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='available_beds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='availability',
            name='total_beds',
            field=models.IntegerField(default=0),
        ),
    ]
