# Generated by Django 3.1.1 on 2024-10-15 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20241015_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availability',
            old_name='available_beds',
            new_name='available',
        ),
        migrations.RenameField(
            model_name='availability',
            old_name='total_beds',
            new_name='total',
        ),
    ]
