# Generated by Django 3.1.1 on 2024-10-15 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20241016_0044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='State',
            new_name='state',
        ),
    ]
